# Default values

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  registry: "gcr.io/triggermesh"
  pullPolicy: "IfNotPresent"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

rbac:
  create: true

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false

resources: {}
  # requests:
  #   cpu: 50m
  #   memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

webhook:
  podAnnotations:
    sidecar.istio.io/inject: 'false'

  podSecurityContext: {}

  securityContext: {}

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
