apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tm-cloud.triggerflow.fullname" . }}
  labels:
    {{- include "tm-cloud.triggerflow.labels" . | nindent 4 }}
{{- include "tm-cloud.imagePullSecrets" . }}
