apiVersion: v2
name: knative-eventing
description: A Helm chart for deploying knative-eventing

type: application

version: 0.5.0

appVersion: "1.4.1"

dependencies:
  - name: knative-operator
    version: 0.5.x
    repository: https://storage.googleapis.com/triggermesh-charts
    condition: knative-operator.enabled
