# Copyright 2021 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "triggermesh.controller.fullname" . }}
  labels:
    {{- include "triggermesh.controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "triggermesh.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "triggermesh.controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "triggermesh.controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.registry }}/triggermesh-controller:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: triggermesh.io
        # Source adapters
        - name: AWSCLOUDWATCHSOURCE_IMAGE
          value: "gcr.io/triggermesh/awscloudwatchsource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWSCLOUDWATCHLOGSSOURCE_IMAGE
          value: "gcr.io/triggermesh/awscloudwatchlogssource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWSCODECOMMITSOURCE_IMAGE
          value: "gcr.io/triggermesh/awscodecommitsource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWSCOGNITOIDENTITYSOURCE_IMAGE
          value: "gcr.io/triggermesh/awscognitoidentitysource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWSCOGNITOUSERPOOLSOURCE_IMAGE
          value: "gcr.io/triggermesh/awscognitouserpoolsource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWSDYNAMODBSOURCE_IMAGE
          value: "gcr.io/triggermesh/awsdynamodbsource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWSKINESISSOURCE_IMAGE
          value: "gcr.io/triggermesh/awskinesissource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWSPERFORMANCEINSIGHTSSOURCE_IMAGE
          value: "gcr.io/triggermesh/awsperformanceinsightssource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWSSNSSOURCE_IMAGE
          value: "gcr.io/triggermesh/awssnssource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWSSQSSOURCE_IMAGE
          value: "gcr.io/triggermesh/awssqssource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AZUREEVENTHUBSOURCE_IMAGE
          value: "gcr.io/triggermesh/azureeventhubsource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AZUREIOTHUBSOURCE_IMAGE
          value: "gcr.io/triggermesh/azureiothubsource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AZUREQUEUESTORAGESOURCE_IMAGE
          value: "gcr.io/triggermesh/azurequeuestoragesource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AZURESERVICEBUSQUEUESOURCE_IMAGE
          value: "gcr.io/triggermesh/azureservicebusqueuesource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: GOOGLECLOUDPUBSUBSOURCE_IMAGE
          value: "gcr.io/triggermesh/googlecloudpubsubsource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: HTTPPOLLERSOURCE_IMAGE
          value: "gcr.io/triggermesh/httppollersource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: OCIMETRICSSOURCE_IMAGE
          value: "gcr.io/triggermesh/ocimetricssource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: SALESFORCESOURCE_IMAGE
          value: "gcr.io/triggermesh/salesforcesource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: SLACKSOURCE_IMAGE
          value: "gcr.io/triggermesh/slacksource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: TWILIOSOURCE_IMAGE
          value: "gcr.io/triggermesh/twiliosource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: WEBHOOKSOURCE_IMAGE
          value: "gcr.io/triggermesh/webhooksource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: ZENDESKSOURCE_IMAGE
          value: "gcr.io/triggermesh/zendesksource-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        # Target adapters
        - name: ALIBABAOSS_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/alibabaosstarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWS_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/awstargets-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: AWS_COMPREHEND_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/awscomprehendtarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: CONFLUENT_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/confluenttarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: DATADOGTARGET_IMAGE
          value: "gcr.io/triggermesh/datadogtarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: ELASTICSEARCH_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/elasticsearchtarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: GOOGLESHEET_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/googlesheettarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: GOOGLECLOUDFIRESTORE_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/googlecloudfirestoretarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: GOOGLECLOUDSTORAGE_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/googlecloudstoragetarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: GOOGLECLOUDWORKFLOWS_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/googlecloudworkflowstarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: HASURATARGET_IMAGE
          value: "gcr.io/triggermesh/hasuratarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: HTTPTARGET_IMAGE
          value: "gcr.io/triggermesh/httptarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: INFRATARGET_IMAGE
          value: "gcr.io/triggermesh/infratarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: JIRATARGET_IMAGE
          value: "gcr.io/triggermesh/jiratarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: LOGZTARGET_IMAGE
          value: "gcr.io/triggermesh/logztarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: ORACLE_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/oracletarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: SALESFORCETARGET_IMAGE
          value: "gcr.io/triggermesh/salesforcetarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: SENDGRID_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/sendgridtarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: SLACK_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/slacktarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: SPLUNKTARGET_IMAGE
          value: "gcr.io/triggermesh/splunktarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: TEKTON_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/tektontarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: TWILIO_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/twiliotarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: UIPATH_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/uipathtarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: ZENDESK_ADAPTER_IMAGE
          value: "gcr.io/triggermesh/zendesktarget-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        # Transformation adapter
        - name: TRANSFORMER_IMAGE
          value: "gcr.io/triggermesh/transformation-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        # Routing adapters
        - name: FILTER_IMAGE
          value: "gcr.io/triggermesh/filter-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: SPLITTER_IMAGE
          value: "gcr.io/triggermesh/splitter-adapter:{{ .Values.image.tag | default .Chart.AppVersion }}"
        # Function Runtimes
        - name: RUNTIME_KLR_PYTHON
          value: gcr.io/triggermesh/knative-lambda-python37:v1.9.1
        - name: RUNTIME_KLR_NODE
          value: gcr.io/triggermesh/knative-lambda-node10:v1.8.1
        - name: RUNTIME_KLR_RUBY
          value: gcr.io/triggermesh/knative-lambda-ruby25:v1.8.1
        # Type-specific options
        - name: TEKTON_REAPING_INTERVAL
          value: 2m
        ports:
        - name: metrics
          containerPort: 9090
        - name: profiling
          containerPort: 8008
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
