apiVersion: v2
name: knative-serving
description: A Helm chart for deploying knative-serving

type: application

version: 0.4.1

appVersion: "1.1.0"

dependencies:
  - name: knative-operator
    version: 0.4.x
    repository: https://storage.googleapis.com/triggermesh-charts
    condition: knative-operator.enabled
