apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  labels:
    {{- include "knative-eventing.labels" . | nindent 4 }}
spec:
  version: {{ .Chart.AppVersion }}
  source:
    ceph:
      enabled: {{ .Values.sources.ceph.enabled }}
    github:
      enabled: {{ .Values.sources.github.enabled }}
    gitlab:
      enabled: {{ .Values.sources.gitlab.enabled }}
    kafka:
      enabled: {{ .Values.sources.kafka.enabled }}
    natss:
      enabled: {{ .Values.sources.natss.enabled }}
    rabbitmq:
      enabled: {{ .Values.sources.rabbitmq.enabled }}
    redis:
      enabled: {{ .Values.sources.redis.enabled }}

  #
  # suitable for up to 2,500 events/sec per replica
  deployments:
  # Broker
  #
  - name: mt-broker-ingress
    resources:
    - container: ingress
      requests:
        cpu: 150m
        memory: 100Mi
      limits:
        cpu: '2'
        memory: 500Mi
  - name: mt-broker-filter
    resources:
    - container: filter
      requests:
        cpu: 500m
        memory: 70Mi
      limits:
        cpu: '4'
        memory: 500Mi
  # In-memory channel
  #
  - name: imc-dispatcher
    resources:
    - container: dispatcher
      requests:
        cpu: 200m
        memory: 250Mi
      limits:
        cpu: '4'
        memory: 1500Mi
