nameOverride: ""

fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  create: true
  annotations: {}
  name: ""

imagePullSecrets: []

image:
  registry: gcr.io
  repository: triggermesh-private/koby-controller
  tag: ""
  pullPolicy: IfNotPresent

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  requests:
    cpu: 20m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}
