nameOverride: ""
fullnameOverride: ""

global:
  image:
    registry: "gcr.io"
    tag: ""
    pullPolicy: "IfNotPresent"
    pullSecrets: []

backend:
  image:
    repository: "triggermesh-private/backend-controller"
    tag: ""

frontend:
  image:
    repository: "triggermesh-private/console"
    tag: "v1.10.1"
  ingress:
    enabled: false
    hostname: chart-example.local
    tls:
      enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      # cert-manager.io/cluster-issuer: letsencrypt-prod

ghbackend:
  image:
    repository: "triggermesh-private/gh-backend"
    tag: ""

triggerflow:
  image:
    repository: "triggermesh-private/triggerflow"
    tag: ""

koby:
  image:
    repository: "triggermesh-private/koby-controller"
    tag: ""

imagepullsecret-patcher:
  enabled: true
  imagePullSecretName: triggermesh-image-pull-secret
  excludedNamespaces: "kube-system"

keycloak:
  enabled: true

  admin:
    username: admin
    password: password

  ingress:
    enabled: false
    hostname: chart-example.local

  realm:
    triggermesh:
      # client_secret:
      registrationAllowed: true

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi

triggermesh:
  enabled: true
