{{- if .Values.global.image.dockercfg }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "koby.fullname" . }}-imagepullsecret
  labels:
    {{- include "koby.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.image.dockercfg | b64enc }}
{{- end }}
